name: flake8
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
      - uses: ./.github/workflows/setup-python.yml
        with:
          python-version: ${{ matrix.python-version }}
      - name: flake8
        run: poetry run flake8 .
